### ISSUE TITLE
Installation instructions

### ISSUE THREAD

**Issue by Tondy** [AllenDowney/ThinkDSP#20]
Hello 

How do I install the thinkdsp module on computer. So I can call the functions.

Cheers

**Comment by AllenDowney** [comment]
It's not really meant to be installed.  I suggest cloning the repo from
GitHub and working in that directory.  There are instructions in the
preface.

Please let me know if that helps.

Allen

**Comment by Tondy** [comment]
Hello Allen Thank you very much. I now have it working with python notebook.

**Comment by TomOHaver** [comment]
I am new to Python/GitHub/Jupyter/Binder/whatever.  I don't even understand "cloning the repo from
GitHub and working in that directory". I've tried the instructions in the preface of your ThinkDSP book.  Excellent work, by the way.  I've tried three different versions of Python in Windows and the version that comes with a Raspberry Pi.  All I get are cryptic error messages, such as "ModuleNotFoundError: No module named 'thinkdsp'".  Any suggestions on what I can try next?

Tom O'Haver, toh@umd.edu
https://terpconnect.umd.edu/~toh/spectrum/SignalProcessingTools.html

**Comment by henzosabiq** [comment]
Here is my manual 'hacks' to make it work. 

1. Clone the repository using git bash
`git clone https://github.com/AllenDowney/ThinkDSP.git`
2. Copy all python files (.py) on the `code` folder
![image](https://user-images.githubusercontent.com/26890032/38121846-ed653e3c-33fb-11e8-94f2-7cdcc573eeef.png)
![image](https://user-images.githubusercontent.com/26890032/38121858-fe2aade2-33fb-11e8-9985-e2ca3cb57a20.png)
3. Locate where you install Python. In Windows, you can try `where python` command in cmd and it will show the path. For example, it gives me : `C:\Users\henzo\AppData\Local\Programs\Python\Python36\python.exe`. 
Copy `C:\Users\<PC names>\AppData\Local\Programs\Python\<python version>\` to windows explorer and press enter. Go to `Lib\site-packages` and you will see names of all Python packages you've installed.
![image](https://user-images.githubusercontent.com/26890032/38121580-596601ea-33fa-11e8-8d0d-8a04e57e0a6f.png)
4. Make a new folder. I name it "AllenDowney" because I respect his amazing work.
5. Paste all the python files from `code` folder here
6. Open all of the python files. Add `AllenDowney.` in front of any import that starts with `think`, and add `as think` as closing. If you find 'import thinkdsp', you should rename it to 'import AllenDowney.thinkdsp as thinkdsp'. 

When you want to 'install' this module to another computer, just copy the AllenDowney folder and move it to `C:\Users\<PC names>\AppData\Local\Programs\Python\<python version>\Lib\site-packages`

**Comment by TomOHaver** [comment]
Thanks for that very specific recommendation.  I'll try it.

**Comment by VicerExciser** [comment]
@henzosabiq Thank you so, so much. Immensely useful advice that makes me feel ignorant for just now discovering.

**Comment by patukes** [comment]
Please I have problem run the import thinkdsp.It still produces error.No module found

**Comment by talhaanwarch** [comment]
> Please I have problem run the import thinkdsp.It still produces error.No module found
please run pip install thinkx in anaconda prompt, it will install think dsp

**Comment by AnthonyMaz** [comment]
Does anyone have a recommendation for my issue below using the thinkx module in Linux? I've installed the module via pip, but I am still unable to reference the module in. I am using pycharm IDE instead of Jupyter.

pip search thinkx | grep think
thinkx (1.1.3)  - Modules supporting books by Allen Downey
pip list | grep thinkx
thinkx                   1.1.3  


Code:
from __future__ import print_function, division

#%matplotlib inline  <-this is commented due to the error
                  %matplotlib inline
                  ^
        SyntaxError: invalid syntax

import thinkdsp
import thinkplot

import numpy as np

from ipywidgets import interact, interactive, fixed
import ipywidgets as widgets
from IPython.display import display


Error:
    import thinkdsp
ModuleNotFoundError: No module named 'thinkdsp'

**Comment by dan54956** [comment]
pip install thinkx

**Comment by yhutagal** [comment]
> It's not really meant to be installed. I suggest cloning the repo from
> GitHub and working in that directory. There are instructions in the
> preface.
> 
> Please let me know if that helps.
> 
> Allen
> 
> On Sat, Apr 2, 2016 at 8:59 PM, Tondy [notifications@github.com](mailto:notifications@github.com) wrote:
> 
> > Hello
> > How do I install the thinkdsp module on computer. So I can call the
> > functions.
> > Cheers
> > —
> > You are receiving this because you are subscribed to this thread.
> > Reply to this email directly or view it on GitHub
> > #20

I was clone it from GitBash. How do i working on that directory?

**Comment by yhutagal** [comment]
> Here is my manual 'hacks' to make it work.
> 
> 1. Clone the repository using git bash
>    `git clone https://github.com/AllenDowney/ThinkDSP.git`
> 2. Copy all python files (.py) on the `code` folder
>    ![image](https://user-images.githubusercontent.com/26890032/38121846-ed653e3c-33fb-11e8-94f2-7cdcc573eeef.png)
>    ![image](https://user-images.githubusercontent.com/26890032/38121858-fe2aade2-33fb-11e8-9985-e2ca3cb57a20.png)
> 3. Locate where you install Python. On Windows, you can try `where python` command in cmd and it will show the path. For example, it gives me : `C:\Users\henzo\AppData\Local\Programs\Python\Python36\python.exe`.
>    Copy `C:\Users\<PC names>\AppData\Local\Programs\Python\<python version>\` to windows explorer and press enter. Go to `Lib\site-packages` and you will see names of all Python packages you've installed.
>    ![image](https://user-images.githubusercontent.com/26890032/38121580-596601ea-33fa-11e8-8d0d-8a04e57e0a6f.png)
> 4. Make a new folder. I name it "AllenDowney" because I respect his amazing work.
> 5. Paste all the python files from `code` folder here
> 6. Open all of the python files. Add `AllenDowney.` in front of any import that starts with `think`, and add `as think` as closing. If you find `import thinkdsp`, you should rename it to `import AllenDowney.thinkdsp as thinkdsp`.
> 
> When you want to 'install' this module to another computer, just copy the AllenDowney folder and move it to `C:\Users\<PC names>\AppData\Local\Programs\Python\<python version>\Lib\site-packages`



> Here is my manual 'hacks' to make it work.
> 
> 1. Clone the repository using git bash
>    `git clone https://github.com/AllenDowney/ThinkDSP.git`
> 2. Copy all python files (.py) on the `code` folder
>    ![image](https://user-images.githubusercontent.com/26890032/38121846-ed653e3c-33fb-11e8-94f2-7cdcc573eeef.png)
>    ![image](https://user-images.githubusercontent.com/26890032/38121858-fe2aade2-33fb-11e8-9985-e2ca3cb57a20.png)
> 3. Locate where you install Python. On Windows, you can try `where python` command in cmd and it will show the path. For example, it gives me : `C:\Users\henzo\AppData\Local\Programs\Python\Python36\python.exe`.
>    Copy `C:\Users\<PC names>\AppData\Local\Programs\Python\<python version>\` to windows explorer and press enter. Go to `Lib\site-packages` and you will see names of all Python packages you've installed.
>    ![image](https://user-images.githubusercontent.com/26890032/38121580-596601ea-33fa-11e8-8d0d-8a04e57e0a6f.png)
> 4. Make a new folder. I name it "AllenDowney" because I respect his amazing work.
> 5. Paste all the python files from `code` folder here
> 6. Open all of the python files. Add `AllenDowney.` in front of any import that starts with `think`, and add `as think` as closing. If you find `import thinkdsp`, you should rename it to `import AllenDowney.thinkdsp as thinkdsp`.
> 
> When you want to 'install' this module to another computer, just copy the AllenDowney folder and move it to `C:\Users\<PC names>\AppData\Local\Programs\Python\<python version>\Lib\site-packages`

I was tried sequencely, but i still got an erro every .py files

D:\Anaconda3\python.exe C:/Users/Yohanees/AppData/Local/Programs/Python/Python37-32/Lib/site-packages/AllenDowney/systems.py
Traceback (most recent call last):
  File "C:/Users/Yohanees/AppData/Local/Programs/Python/Python37-32/Lib/site-packages/AllenDowney/systems.py", line 10, in <module>
    import AllenDowney.thinkdsp as thinkdsp
ModuleNotFoundError: No module named 'AllenDowney'

**Comment by janarthan-j** [comment]
Try to install the "thinkx" as it mentions in this link https://anaconda.org/conda-forge/thinkx  
It's worked for me!
This solution for the Anaconda and pycharm users.

To install this package with conda run one of the following:
conda install -c conda-forge thinkx
conda install -c conda-forge/label/cf201901 thinkx

**Comment by psjpang** [comment]
> Try to install the "thinkx" as it mentions in this link https://anaconda.org/conda-forge/thinkx
> It's worked for me!
> This solution for the Anaconda and pycharm users.
> 
> To install this package with conda run one of the following:
> conda install -c conda-forge thinkx
> conda install -c conda-forge/label/cf201901 thinkx



hi～ I tried to run like this in pycharm, but it still fails. If you can, can you take a screenshot of where you added these two lines of code?
