### ISSUE TITLE
Playback audio

### ISSUE THREAD

**Issue by Israelojo** [AllenDowney/ThinkDSP#64]
I can't get the wav files to playback when I run the code in spyder

**Comment by Israelojo** [comment]
make_audio() and Audio() don't seem to work. Any help in solving this is highly appreciated!

**Comment by RonFredericks** [comment]
One problem is that the wav player included in this package called aplay is only available for linux boxes. If you have linux than make sure it is installed where ThinkDSP can find it. Otherwise you will need to find an alternative wav player. I am on Windows so I came up with this open source alternative that should work on linux or windows using the simpleaudio module - see attached.
[audio_player2.zip](https://github.com/AllenDowney/ThinkDSP/files/3454070/audio_player2.zip)

**Comment by AllenDowney** [comment]
In Chapter 1 I show two ways to play sound, one using an external player, aplay.  If you can install aplay for your system, it should work.  If not, you can try the second way, which uses the Audio object from Ipython.display.  That should work on any system with a complete Jupyter installation.

I don't recommend running the notebooks in Spyder.

**Comment by AllenDowney** [comment]
Closing for now, but please reopen if you have questions.

**Comment by jwickard** [comment]
On Mac you can `brew install sox`  and edit thinkdsp.py to use `play` instead of `aplay` as the cli command.
